apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category
  template:
    metadata:
      labels:
        app: category
    spec:
      automountServiceAccountToken: false
      containers:
      - name: category-container
        image: ivanazare/category:v1.0.0  # Use uma tag específica em vez de 'latest'
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: category-config
              key: DATABASE_URL
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: category-config
              key: APP_ENV
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: category-config
              key: APP_VERSION
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5